Set get frames public
joomcode/errorx pull request #41
Opened 2023-01-21 08:37 UTC by ldreux

2023-01-23 11:44 UTC, PeterIvanov requested changes
This PR requires a description. 
The first thing to know here is a use case. I'm fairly sure that it's better to provide utilities for it, if it's a valid case, rather than exposing some internals from `errorx`.

2023-01-23 11:44 UTC, PeterIvanov commented on stacktrace.go
> +	// tuned so that in all control paths of error creation the first Frame is useful
This, I'm sure, is an unintended change.

2023-01-23 11:44 UTC, PeterIvanov commented on error.go
> +// GetFrames export stacktrace as frame slice.
```suggestion
// GetFrames exports stacktrace as frame slice.
```

2023-07-11 09:06 UTC, PeterIvanov commented
Maybe we adopt this exact use case? 
Instead of API focused on just exposing stack frames, make an api for conversion. This would highlight that you don't need to extract this information as-is, but if you need to feed it to some system with custom stack frames format, you can.
Such conversion API can also be based on interface for errorx frame, not the actual representation, as an added bonus. 
What's your view on such idea?

2023-07-18 11:17 UTC, PeterIvanov requested changes
Pending an answer to the question above, marking this PR as `Request changes` for now.

2024-01-15 12:10 UTC, reaganiwadha commented
For monitoring tools like `github.com/getsentry/sentry-go`, it's important to expose the callstack so the error can be traced. 

https://github.com/getsentry/sentry-go/blob/824589bd5be49de6242d5f867a94c7df05510a4e/stacktrace.go#L74

This is how Sentry extracts stack trace from other error libraries. While I don't think `errorx` should necessarily adhere to the way Sentry parses stack trace, an exposed API to get the frames from the `Error` should be available for custom stack trace parsing.

2024-01-15 12:16 UTC, reaganiwadha commented
> Instead of API focused on just exposing stack frames, make an api for conversion. This would highlight that you don't need to extract this information as-is, but if you need to feed it to some system with custom stack frames format, you can.

Im not sure how a conversion API for call stack works, can you provide an example?

2024-01-16 14:54 UTC, PeterIvanov commented
As far as I can recall, the idea was that we add an API like this:
```
func (e *Error) ExportStackFrames(originalFrames []FrameInterface) any
```
This way, we:
1. Hint that extracting stack frames is not an intended high-level API for dealing with errors
2. Hide behind the interface to avoid, say, marshalling issues

2024-01-16 14:56 UTC, PeterIvanov commented
In this PR, the second point is already addressed, so I'm generally OK with that. Just asked for an opinion on an idea.

2026-07-17 07:26 UTC, closed without merging